name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.1.8937393" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          cp app/build/outputs/apk/release/app-universal-release.apk app/build/outputs/apk/release/EhViewer-universal-A12+.apk
          cp app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/EhViewer-arm64-v8a-A12+.apk
          cp app/build/outputs/apk/release/app-x86_64-release.apk app/build/outputs/apk/release/EhViewer-x86_64-A12+.apk
          cp app/build/outputs/apk/release/app-x86-release.apk app/build/outputs/apk/release/EhViewer-x86-A12+.apk
          cp app/build/outputs/apk/release/app-armeabi-v7a-release.apk app/build/outputs/apk/release/EhViewer-armeabi-v7a-A12+.apk

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          discussion_category_name: Announcements
          files: |
            app/build/outputs/apk/release/EhViewer-universal-A12+.apk
            app/build/outputs/apk/release/EhViewer-arm64-v8a-A12+.apk
            app/build/outputs/apk/release/EhViewer-x86_64-A12+.apk
            app/build/outputs/apk/release/EhViewer-x86-A12+.apk
            app/build/outputs/apk/release/EhViewer-armeabi-v7a-A12+.apk

      - name: Collect Apks
        run: |
          mkdir app/build/outputs/apk/release/fdroid
          cp app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/fdroid/EhViewer-v$GITHUB_REF_NAME.apk
          cp app/build/outputs/apk/release/app-armeabi-v7a-release.apk app/build/outputs/apk/release/fdroid/EhViewer-v$GITHUB_REF_NAME-armv7.apk

      - name: Push Apks
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
         SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: app/build/outputs/apk/release/fdroid
          destination-github-username: Ehviewer-Overhauled
          destination-repository-name: fdroid-repo
          user-name: 'github-actions[bot]'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          target-branch: deploy
          commit-message: Add apks from $GITHUB_REF
          target-directory: fdroid/tmp-apks